### ISSUE TITLE
serialization writer doesn't escape double quotes in strings

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-serialization-json-go#11]
If a string value contains a single quote the serialization writer doesn't escape it and this produces an invalid JSON representation.

A good example of that is the OData etag field (when trying to serialize to storage after retrieving from the service)

```json
"@odata.etag": "W/\"CQAAABYAAAAs+XSiyjZdS4Rhtwk0v1pGAAC5bsJ2\""
``` 

ends up producing

```json
"@odata.etag": "W/"CQAAABYAAAAs+XSiyjZdS4Rhtwk0v1pGAAC5bsJ2""
```

**Comment by dadams39** [comment]
Is this related to the PR awaiting review?

PR https://github.com/microsoft/kiota-serialization-json-go/pull/6

**Comment by baywet** [comment]
For the string part yes. For the byte one and the comma trimming no. The author hasn't replied to my initial clarification request and it's missing unit tests. Feel free to submit one focused on the quote issue. We'll resolve conflicts if the author replies.
