### ISSUE TITLE
ByteValue Stored as Int64 Should it be Base64

### ISSUE THREAD

**Issue by dadams39** [microsoft/kiota-serialization-json-go#13]
Related to Issue #12 

When writing the tests to verify outcomes of base data structures, the code is noted to have the same output as in the previous issue. This failure is going to be fixed in an upcoming [ PR. ](https://github.com/microsoft/kiota-serialization-json-go/pull/14) 

Upon inspection, it is noted that the previous behavior was to cast the byte into an int and save it as an int. However, when saving a byte array, the values are saved in base 64. If this is the intended behavior for both data structures,
 `func TestWriteByteValue(t *testing.T) ` should be correct.
 - [ ] Inspection of PR and function TestWriteByteValue

**Comment by baywet** [comment]
Hi @dadams39 
Thanks for reporting this.
The intent was to have a binary (byte array) value serialized as a base64 encoded value in the JSON payload.
If the intent is not clear from the description, please feel free to update it in a pull request.

**Comment by dadams39** [comment]
This is how the tests are configured the additional tests were conditioned. PR https://github.com/microsoft/kiota-serialization-json-go/pull/14 is free to be merged with no additional changes from my end.

**Comment by baywet** [comment]
thanks for confirming!
