### ISSUE TITLE
[BUG] When using (*JsonParseNode).GetXValue methods it panics

### ISSUE THREAD

**Issue by michaeldcanady** [microsoft/kiota-serialization-json-go#142]
When using (*JsonParseNode).GetXValue methods it panics due to the value being assert as specific type when it's not.

module version: 1.0.7
golang version: 1.22.5
OS: Window 11

minimum reproducible code:
```golang
package main

import (
	"log"

	jsonserialization "github.com/microsoft/kiota-serialization-json-go"
)

func main() {
	data := []byte(`"I am not a float"`)
	node, _ := jsonserialization.NewJsonParseNode(data)
	float, err := node.GetFloat64Value()
	if err != nil {
		log.Print(err)
		return
	}
	log.Print(float)
	return
}
```

console output:
```bash
panic: interface conversion: interface {} is *string, not *float64

goroutine 1 [running]:
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetFloat64Value(0xc000068620)
	.../go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.7/json_parse_node.go:463 +0xb2
main.main()
	.../min.go:12 +0x105
```

**Comment by michaeldcanady** [comment]
would probably be easiest to just use something like this:
```golang
func GetValue[T any](in interface{}) (*T, error) {
	var zero *T

	if in == nil {
		return nil, nil
	}

	val, ok := in.(*T)
	if !ok {
		return nil, fmt.Errorf("Expected type: %T, got %T", zero, in)
	}

	return val, nil
}
```
in each method

**Comment by andrueastman** [comment]
Thanks for raising this @michaeldcanady 

I believe the suggestion here is valid. The code seems to assume the type is surely known ahead of time but such a failure should indeed be propagated through the error return.

Any chance this is something you'd be willing to submit a PR for?

**Comment by michaeldcanady** [comment]
@andrueastman
1. Do we want anything that _can be_ of type X to be converted (ex: the value is 1, which is a number, but the user calls GetStringValue, should it error or return "1".)?

**Comment by andrueastman** [comment]
@andrueastman I believe if it's possible for the conversion to occur, we should return the value. 

As this is a Json library, the parsed json would ideally have string surrounded by double quotes. So, calling `GetFloat64Value` on a json value surrounded by double quotes should fail(its a string). Similarly, if the json value is a number, it won't have doulbe quotes, so calling `GetStringValue` value would also fail.

This is however different from types derived from strings like `Guid` where you can still get a string value from it or get the Guid value. Let us know if you have any more questions.

**Comment by michaeldcanady** [comment]
One more, hopefully, the following test from [.\intersection_type_wrapper_test.go](https://github.com/microsoft/kiota-serialization-json-go/blob/main/intersection_type_wrapper_test.go#L33) is failing - assuming it was passing before - it seems to be failing since the new parsing won't handle the int as string.
```golang
func TestItParsesIntersectionTypeComplexProperty2(t *testing.T) {
	source := "{\"displayName\":\"McGill\",\"officeLocation\":\"Montreal\", \"id\": 10}"
	sourceArray := []byte(source)
	parseNode, err := NewJsonParseNode(sourceArray)

	if err != nil {
		t.Error(err)
	}
	result, err := parseNode.GetObjectValue(internal.CreateIntersectionTypeMockFromDiscriminator)
	if err != nil {
		t.Error(err) // value '10' is not compatible with type string
	}
	assert.NotNil(t, result) // Expected value not to be nil.
	cast, ok := result.(internal.IntersectionTypeMockable)
	assert.True(t, ok) // panic: runtime error: invalid memory address or nil pointer dereference
	assert.NotNil(t, cast.GetComposedType1())
	assert.NotNil(t, cast.GetComposedType2())
	assert.Nil(t, cast.GetStringValue())
	assert.Nil(t, cast.GetComposedType3())
	assert.Nil(t, cast.GetComposedType1().GetId())
	assert.Nil(t, cast.GetComposedType2().GetId()) // it's expected to be null since we have conflicting properties here and the parser will only try one to avoid having to brute its way through
	assert.Equal(t, "McGill", *cast.GetComposedType2().GetDisplayName())
}
```

**Comment by michaeldcanady** [comment]
> As this is a Json library, the parsed json would ideally have string surrounded by double quotes. So, calling `GetFloat64Value` on a json value surrounded by double quotes should fail(its a string). Similarly, if the json value is a number, it won't have doulbe quotes, so calling `GetStringValue` value would also fail.

Hello @saviorand! Thank you for your question, Assuming you’re referenced JSON is like the following:
```json
{
"Key":"1"
}
```
Then yes.

the goal is to parse what the underlying type is. So in the above example even though it’s a stringified integer, the value is a string. I included the discussion point where this was decided.

**Comment by michaeldcanady** [comment]
@saviorand I unfortunately do not.
