### ISSUE TITLE
SerialWriter Incorrect Format with additional data

### ISSUE THREAD

**Issue by dadams39** [microsoft/kiota-serialization-json-go#17]
When Writer serializes object, a comma is missing following the `@odata.etag` entry:

```
"id":"AAMkAGQ1NzViZTdhLTEwMTMtNGJjNi05YWI2LTg4NWRlZDA2Y2UxOABGAAAAAAAPvVwUramXT7jlSGpVU8_7BwB8wYc0thTTTYl3RpEYIUq_AAAAAAETAAB8wYc0thTTTYl3RpEYIUq_AAAYy16iAAA=",
"@odata.etag":"W/\"CQAAABYAAAB8wYc0thTTTYl3RpEYIUq+AAAZEpnr\"""categories":[],"changeKey"
```

**Comment by baywet** [comment]
Thanks for reporting this.
QQ: the etag is not a property (no Get/Set odata etag methods on the model), correct? it's part of the additional data manager.
If so it's possible that the additional data manager writing might be missing a coma.

**Comment by dadams39** [comment]
That is correct the model does not add that data.

**Comment by baywet** [comment]
https://www.github.com/microsoft/kiota-serialization-json-go/tree/main/json_serialization_writer.go line 585
