### ISSUE TITLE
SerializationWriter producing Incomplete Json objects

### ISSUE THREAD

**Issue by dadams39** [microsoft/kiota-serialization-json-go#18]
Related to Issue #17 

When comma is added to payload, parse node still fails to create a message object.
View full data on [Pastebin](https://pastebin.com/2jugAnEx) expires in 24 hours from post.
The data is attempted imported in this way:
```
  parseNode, err := absser.DefaultParseNodeFactoryInstance.GetRootParseNode("application/json",bytes)
    if err != nil{
        fmt.Errorf("Unable to create parseNode:%v\n", err)
    }
    aMessage, err := models.CreateMessageFromDiscriminatorValue( parseNode )
    if err != nil{
        fmt.Printf("Unable to create message: %v\n", err)
    }
    fmt.Printf("Message: %T %v\n", parseNode, parseNode)
    fmt.Printf("Message: %T %v\n", aMessage, aMessage)
```
Results
```
Message: *jsonserialization.JsonParseNode &{0x140002854f0}
Message: *models.Message &{{{map[] <nil>} [] <nil> <nil> <nil>} [] [] <nil> <nil> [] <nil> [] [] <nil> <nil> <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> [] <nil> <nil> [] <nil> <nil> [] <nil> [] <nil> <nil>}
```
When attempted as described in https://github.com/microsoftgraph/msgraph-sdk-go/discussions/141 where
`        deserializedValue, err := parseNode.GetObjectValue(models.CreateMessageFromDiscriminatorValue)`
replaces the aMessage, err assignment
```
Unable to create message: value is not an object
Message: *jsonserialization.JsonParseNode &{0x14000429d40}
```
Thoughts?

**Comment by baywet** [comment]
so if I'm understanding things well your application is trying to parse something from a persistence store it previously wrote using the serialization writer? and it's failing to do so because the serialization result was invalid JSON?
If so, why did you create a second issue for the same root cause?
If not, can you expand a bit on the context for my understanding please?

**Comment by baywet** [comment]
Is the fact the pastebin is invalid JSON/incomplete on purpose/does it reflect the situation accurately? or is it a copy pasting issue?

**Comment by dadams39** [comment]
For example could the failure be caused because there is not an enclosing:
```
 "value": [ .... 
 ```
 Above the input?

**Comment by dadams39** [comment]
The Json is the result of the writer. In all of the files they end in the exact same manner. 

```go
message := pageItem.(models.Messageable)
fmt.Printf("%s\n", *message.GetSubject())
err := message.Serialize(myWriter)
if err != nil {
                        hasFailed = err
}
byteArray, _  = myWriter.GetSerializedContent()

err := os.WriteFile(aFile, byteArray, 0644)
```

**Comment by baywet** [comment]
are you getting any error when calling `myWriter.GetSerializedContent()`?

**Comment by dadams39** [comment]
I am getting not getting any errors.

**Comment by baywet** [comment]
~~interestingly the weblink [is the last property message writes](https://github.com/microsoftgraph/msgraph-sdk-go/blob/80186093e26af8b4046b4eb89a342c4a8af0641c/models/message.go#L883) and the serialization process doesn't get [to trimming the last comma](https://github.com/microsoft/kiota-serialization-json-go/blob/bbc5404108fe6483228973d44c277de2ba1b27df/json_serialization_writer.go#L247) after that.~~

You need to change this

```diff
-err := message.Serialize(myWriter)
+err := myWriter.WriteObjectValue(message)
```

**Comment by dadams39** [comment]
This produces the correct object. Well outside of Issue #17.
