### ISSUE TITLE
Improper JSON serialization of Time values

### ISSUE THREAD

**Issue by mbarnes** [microsoft/kiota-serialization-json-go#4]
I was debugging some mysterious "400 Bad Request" errors from [msgraph-sdk-go](https://github.com/microsoftgraph/msgraph-sdk-go) and found that this chunk of code:
```
	credential := msgraph_models.NewPasswordCredential()
	credential.SetDisplayName(&displayName)
	credential.SetEndDateTime(&endDateTime)

	requestBody := msgraph_apps_addpw.NewPasswordCredentialRequestBody()
	requestBody.SetPasswordCredential(credential)
	options := &msgraph_apps_addpw.AddPasswordRequestBuilderPostOptions{
		Body: requestBody,
	}
	result, err := graph.ApplicationsById(id).AddPassword().Post(options)
```
was resulting in this request body:
```
{"passwordCredential":{"displayName":"test","endDateTime":2023-04-13 14:35:55.527758542 -0400 EDT}}
```
and this OData error:
```
{
    "error": {
        "code": "BadRequest",
        "message":"Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format."
        ...
    }
}
```

The format of `endDateTime` is wrong.

I believe DateTimeOffset values must be in ISO 8601-1:2019 format, at least according to [.NET docs](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support).
```
{"passwordCredential":{"displayName":"test","endDateTime":2023-04-13T14:35:55-04:00}}
```
The current code [just converts to a string](https://github.com/microsoft/kiota-serialization-json-go/blob/c708f8083763b0fd22e1644e69a7be30d39ab874/json_serialization_writer.go#L165-L167).

**Comment by baywet** [comment]
Hi @mbarnes ,
Thanks for reaching out and reporting this.
You are right, it should follow the Iso 8601 format according to the docs https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http.
Also, the fact that double quotes are missing is another defect. All the write date/time/duration methods should call write string and not write raw.

Would you be willing to submit a pull request?

**Comment by mbarnes** [comment]
Sure (and I know I still owe you [another one](https://github.com/microsoftgraph/msgraph-sdk-go/issues/110#issuecomment-1070961933)).

**Comment by baywet** [comment]
Thanks a lot! If you could prioritize this one over the other one please? And don't hesitate to let us know if you need help or to hand them back!
