### ISSUE TITLE
Serialization performance

### ISSUE THREAD

**Issue by eric-millin** [microsoft/kiota-serialization-json-go#74]
`JsonSerializationWriter` looks like it could be a good deal more efficient. With a small change I improved performance by about 50% and the tests pass. Those numbers come from benchmarks, so they only mean so much.  I can PR the change at some point if you're interested, if not, no worries.

https://github.com/eric-millin/kiota-serialization-json-go/commit/13667903e9264e122cd7394a2c0a713a3a33ef7b

Here are the differences in the benchmarks

```
Current   	  111204	     10472 ns/op	   20806 B/op	     211 allocs/op
AfterChange 	  170420	      6276 ns/op	    2095 B/op	     100 allocs/op
```

**Comment by baywet** [comment]
Thanks for the suggestion. We'd be very happy to see that performance improvement in the code-base assuming it doesn't trade-off functionality.

**Comment by eric-millin** [comment]
We're not really impacted by this issues. Perhaps I'll do it on a Friday afternoon.

**Comment by eric-millin** [comment]
For posterity's sake (and my own memory if I turn back to this) I'll note that there's a small bug in my code that's probably easily fixed. There needs to be a separate slice that tracks property separator indices. Those can be recorded in `writeRawValue`.  Then you know the location of the separators `trimLastPropertySeparator`. That prevents mistaking a character in raw text for a separator.

Sum total is you're no longer doing a bunch of string concatenations and can reuse buffers.
