### ISSUE TITLE
Unable to serialize large ISODurationValue

### ISSUE THREAD

**Issue by dadams39** [microsoft/kiota-serialization-json-go#9]
While testing the JsonSerializationWriter with the following test:

```
func TestDuration( t *testing.T ){
    jw := NewJsonSerializationWriter()
    duration := serial.NewDuration(5, 2, 4, 14, 30, 12, 45)
    err := jw.WriteISODurationValue("Extended", duration)
    if err != nil{
        t.Errorf("Failure: %v\n", err)
    }
}   
```

Received the following errors:
```
panic: weeks are not allowed with years or months [recovered]                                                                                                                                  
        panic: weeks are not allowed with years or months   
```
Nothing in the originating [library](https://github.com/microsoft/kiota-abstractions-go) suggests that durations cannot be larger than weeks. NOTE::  Changing the leading two integers to `0` will allow for the test to pass.

**Comment by baywet** [comment]
Hi @dadams39
Thank you for reaching out and for trying the go sdk.
This is by design, the ISO spec doesn't allow to use both weeks and years in the same value.
But you can perfectly use them separately.
Let me know if you have additional questions.
