### ISSUE TITLE
Panic deserializing response when some datacenters return a string instead of an int for OneDrive item field

### ISSUE THREAD

**Issue by ashmrtn** [microsoft/kiota-serialization-json-go#98]
I've recently started seeing panics from the kiota-serialization-json-go library when attempting to deserialize a response from the `user/<userID>/drive/root/delta` (user's OneDrive delta) endpoint. The cause of the failure is an item that has had extra information attached to it by OneDrive. Specifically, it seems that some information about the image was populated including the image dimensions. The image orientation appears to have been partially populated in the sense that now it's not nil/null but instead empty. A minimal sample response for the failing item is
```json
{
    "@odata.type": "#microsoft.graph.driveItem",
    "@odata.etag": "\"{787C2A2D-DF31-4BAF-9ACC-2FB7D14A4029},1\"",
    "createdDateTime": "2023-06-23T17:52:58Z",
    "id": "01BAFL6LRNFJ6HQMO7V5FZVTBPW7IUUQBJ",
    "lastModifiedDateTime": "2023-06-23T17:52:58Z",
    "name": "woohoo_homer.png",
    "photo": {
        "orientation": ""
    },
    "size": 180589
}
```

This request had an `x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"002","RoleInstance":"MWH0EPF0009A922"}}` header.

When receiving a response for this particular image the library panics trying to cast a string into a float (which is later cast to an int). The relevant stack trace for the failure is
```text
panic: interface conversion: interface {} is *string, not *float64 [recovered]
  panic: interface conversion: interface {} is *string, not *float64

goroutine 51 [running]:
testing.tRunner.func1.2({0x1072a47c0, 0x14000bba960})
  /opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
  /opt/homebrew/Cellar/go/1.20.3/libexec/src/testing/testing.go:1529 +0x384
panic({0x1072a47c0, 0x14000bba960})
  /opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:884 +0x204
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetFloat64Value(...)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:406
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetInt32Value(0x140006a7718?)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:411 +0x9c
github.com/microsoftgraph/msgraph-sdk-go/models.(*Photo).GetFieldDeserializers.func9({0x107d71e80?, 0x140008a6d00?})
  /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/photo.go:170 +0x34
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetObjectValue(0x140008a6d20, 0x140008b25a8?)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:225 +0x368
github.com/microsoftgraph/msgraph-sdk-go/models.(*DriveItem).GetFieldDeserializers.func18({0x107d71e80?, 0x140008a6d20?})
  /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/drive_item.go:283 +0x3c
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetObjectValue(0x140008a6d60, 0x0?)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:225 +0x368
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetCollectionOfObjectValues(0x140008a76a0?, 0x107d3c4c8)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:251 +0x17c
github.com/microsoftgraph/msgraph-sdk-go/drives.(*ItemItemsItemDeltaResponse).GetFieldDeserializers.func1({0x107d71e80?, 0x140008a7660?})
  /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/drives/item_items_item_delta_response.go:27 +0x3c
github.com/microsoft/kiota-serialization-json-go.(*JsonParseNode).GetObjectValue(0x140008a7680, 0x107d65500?)
  /go/pkg/mod/github.com/microsoft/kiota-serialization-json-go@v1.0.2/json_parse_node.go:225 +0x368
github.com/microsoft/kiota-http-go.(*NetHttpRequestAdapter).Send(0x1400004d400, {0x107d65500?, 0x14000374c90?}, 0x14000606cc0, 0x14000374cf0?, 0x140007e9c70?)
  /go/pkg/mod/github.com/microsoft/kiota-http-go@v1.0.0/nethttp_request_adapter.go:359 +0x294
github.com/microsoftgraph/msgraph-sdk-go/drives.(*ItemItemsItemDeltaRequestBuilder).Get(0x14000374b40, {0x107d65500, 0x14000374c90}, 0x1065abdc8?)
  /go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/drives/item_items_item_delta_request_builder.go:62 +0x104
```

A coworker and I have been going back and forth trying to debug this and so far we've seen it on requests marked with `West US 2` but not `West US` (we mostly end up hitting those two DCs it seems). Attempts to get other images in OneDrive to have the additional metadata that seems to cause this error have been unsuccessful

Is there any way to gracefully handle this sort of situation?

**Comment by baywet** [comment]
Thanks for reporting this. While we could add fault tolerance here, the service should honor the contract.
In the [service metadata](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsAndErrorsv1.0.xml) the field is described as Edm.Int16. Per OData conventions, it should never return an empty string.
My suggestion at this point is that you open a support ticket so the service team can investigate and fix this inconsistent payload.

**Comment by ashmrtn** [comment]
sorry, this got pushed down on the pile of things to do. Unfortunately I got bounced around a few times while trying to find the correct team to contact to get this fixed. We've been able to work around the issue and the original cause of the error (the photo attribute in OneDrive) may have been fixed, but there's no guarantees that we won't hit something similar in the future

**Comment by baywet** [comment]
thanks for reverting, closing
